### ISSUE TITLE
Demand Modifier

### ISSUE THREAD

**Issue by robbiemu** [WhitefangGreytail/WG_RealisticCitySkylines#13]
Hi I am looking at the code here, I notice that the demandmodifier.cs has a comment and a snippet that suggests that it is disabling residential levelup. Is that correct?

**Comment by EC-O-DE** [comment]
I've been usin the mod, with configured XML, and no - buildings do level up.

**Comment by WhitefangGreytail** [comment]
I have no idea how I missed this.

The code is to disable residential buildings from reporting that land value is too low. This is an open issue, although I'm not sure if it is still accurate.
