### ISSUE TITLE
Population density by wealth

### ISSUE THREAD

**Issue by kevinpeno** [WhitefangGreytail/WG_RealisticCitySkylines#22]
One thing that is pretty common is that people tend to have roommates or rent duplexes, etc, when wealth is low. I was wondering if there was a way to tweak the system to, regardless of housing model used, trigger a similar result.

**Comment by WhitefangGreytail** [comment]
Co-rentals is not easily done. The households are family centric.
Sorry :(

**Comment by kevinpeno** [comment]
Ah, that's too bad. No types of family or way to control family member mixing? Honestly I'm just looking for a tweak family member numbers depending on wealth, education, and other factors. Could allow for some additional diversity in cities instead of just seeing 2 adults and 3 children in every house.

**Comment by WhitefangGreytail** [comment]
While it could be nice, for now it's kind of low priority for a different mod. I can do that with a resident overhaul mod... but it will wait till I fix removal of excess workers from an upgraded buildling.
