### ISSUE TITLE
Education issues

### ISSUE THREAD

**Issue by armarayo** [WhitefangGreytail/WG_RealisticCitySkylines#9]
Education issues

This mod is making everybody (at certain age) go to university, but elementary dropout is some 75% and high school dropout is shocking 50%.

I do have the education policy on, but I'm sure I noticed this before I started using this mod.

I do not use the "Dropouts" -mod.

Could perhaps the education versus job sectors be removed from this mod?

**Comment by WhitefangGreytail** [comment]
The education versus job section should not be causing the dropout issue. It's an improper removal of citizens for low density households which is also affecting high density.

If you change the experimental flag in the first line of the XML to false it'll disable the removal of citizens. This has been reported as a fix and you will need to load the city twice for low density households to have correct values as stated in the XML.

I am trying my fastest to resolve the issue.

**Comment by armarayo** [comment]
Thank you :) be fast :)

**Comment by WhitefangGreytail** [comment]
I believe I have fixed the citizen issue since I no longer try to delete them.
